name: inditab_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  velocity_x: ^3.5.1
  flutter_login: ^4.0.0
  google_fonts: ^3.0.1
  extended_image: ^6.2.1
  cloud_firestore: ^3.4.5
  google_maps_flutter: ^2.1.12
  auth_buttons: ^3.0.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  paytm_allinonesdk: ^1.1.8

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/.

