// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlGut-nVDoDsFtz4W5xLLUVl5457KMpY',
    appId: '1:602095360919:web:e80a180cb919d1c8c3c2d2',
    messagingSenderId: '602095360919',
    projectId: 'inditabtask',
    authDomain: 'inditabtask.firebaseapp.com',
    storageBucket: 'inditabtask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOE8OXvwrZlA1G_zGkUft_EwFibHOYv4',
    appId: '1:602095360919:android:7886323b8564dd07c3c2d2',
    messagingSenderId: '602095360919',
    projectId: 'inditabtask',
    storageBucket: 'inditabtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkXu5FK1fgyjgLGhgf7JFI0sPKKtHf3U',
    appId: '1:602095360919:ios:9ff16727367617fec3c2d2',
    messagingSenderId: '602095360919',
    projectId: 'inditabtask',
    storageBucket: 'inditabtask.appspot.com',
    iosClientId: '602095360919-hllbr31tm7clhoum15bap2p5ujur7o7o.apps.googleusercontent.com',
    iosBundleId: 'com.hrithik.inditabtask.inditabTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkXu5FK1fgyjgLGhgf7JFI0sPKKtHf3U',
    appId: '1:602095360919:ios:9ff16727367617fec3c2d2',
    messagingSenderId: '602095360919',
    projectId: 'inditabtask',
    storageBucket: 'inditabtask.appspot.com',
    iosClientId: '602095360919-hllbr31tm7clhoum15bap2p5ujur7o7o.apps.googleusercontent.com',
    iosBundleId: 'com.hrithik.inditabtask.inditabTask',
  );
}
